export const presets = {
  baseline: {
    label: "Simple start",
    values: {
      rowCount: 1000,
      dataSource: "faker",
      cache: true,
      buildStrategy: "inner_html",
      virtualization: "off",
      bufferRows: 8,
      layoutStrategy: "interleaved",
      containment: {
        contain: false,
        contentVisibility: false,
        willChange: false,
      },
      scheduling: "synchronous",
      chunkRows: 200,
      eventStrategy: "delegated",
      memoryStrategy: "cleanup",
    },
  },
  blocking: {
    label: "Freezes the tab",
    values: {
      rowCount: 10000,
      dataSource: "faker",
      cache: false,
      buildStrategy: "create_element",
      virtualization: "off",
      bufferRows: 8,
      layoutStrategy: "interleaved",
      containment: {
        contain: false,
        contentVisibility: false,
        willChange: false,
      },
      scheduling: "synchronous",
      chunkRows: 200,
      eventStrategy: "per_row",
      memoryStrategy: "retain",
    },
  },
  chunked: {
    label: "Stays responsive",
    values: {
      rowCount: 10000,
      dataSource: "faker",
      cache: false,
      buildStrategy: "inner_html",
      virtualization: "off",
      bufferRows: 8,
      layoutStrategy: "batched",
      containment: {
        contain: false,
        contentVisibility: true,
        willChange: false,
      },
      scheduling: "yield",
      chunkRows: 500,
      eventStrategy: "delegated",
      memoryStrategy: "cleanup",
    },
  },
  smooth: {
    label: "Fast at scale",
    values: {
      rowCount: 100000,
      dataSource: "cheap",
      cache: true,
      buildStrategy: "recycle",
      virtualization: "windowed",
      bufferRows: 8,
      layoutStrategy: "batched",
      containment: {
        contain: true,
        contentVisibility: false,
        willChange: true,
      },
      scheduling: "synchronous",
      chunkRows: 200,
      eventStrategy: "delegated",
      memoryStrategy: "cleanup",
    },
  },
  unbounded: {
    label: "A million rows",
    values: {
      rowCount: 1000000,
      dataSource: "cheap",
      cache: true,
      buildStrategy: "recycle",
      virtualization: "windowed_scaled",
      bufferRows: 12,
      layoutStrategy: "batched",
      containment: {
        contain: true,
        contentVisibility: false,
        willChange: true,
      },
      scheduling: "synchronous",
      chunkRows: 200,
      eventStrategy: "delegated",
      memoryStrategy: "cleanup",
    },
  },
};
